### ISSUE TITLE
Rebuild permissions system.

### ISSUE THREAD

**Issue by insertish** [revoltchat/delta#104]
For #6 and #4.

Current hierarchy:
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/38285861/155381292-50ef99ce-da99-4455-84c0-4ee3b6499e83.png">

**Comment by insertish** [comment]
Ideally, we could build it similar to how Discord inherits permissions so that there's not much of a learning curve.

https://support.discord.com/hc/en-us/articles/206141927-How-is-the-permission-hierarchy-structured-

Although, it would be worth adding role permission deny.

**Comment by sairam4123** [comment]
Please do make sure that roles follow Hierarchy.

**Comment by erkinalp** [comment]
> Ideally, we could build it similar to how Discord inherits permissions so that there's not much of a learning curve.

Discord does not inherit permissions from the parent category. Revolt could depart from that and actually inherit from the parent category. Also to mention, it uses an "explicit allow wins" system which is inconvenient in a lot of respects. "Explicit deny wins" is better suited to express permissions.

**Comment by insertish** [comment]
Now closes #4 as of https://github.com/revoltchat/quark/commit/d2e49a61b644a427a0d57991b978a6eb9858911f. (This repo will be public once license is added.)

**Comment by insertish** [comment]
The following does not account for categories yet, still sorting out the data model.
Current permission hierarchy looks like this:
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/38285861/155206969-f22badb1-4b9c-40fd-96dd-e6ef410e8a7e.png">

I am currently working to implement this.

**Comment by erkinalp** [comment]
@insertish That one is pretty much explicit allow wins, which tends to stabilise around uncontrollable power.

**Comment by erkinalp** [comment]
Allows then denies, so *explicit deny wins*. This seems sane to me. After all, lockout is better than power out of control.

**Comment by insertish** [comment]
Fix relevant issue https://github.com/revoltchat/revite/issues/84 while we're at it.
