### ISSUE TITLE
Replace members sidebar fetch mechanism.

### ISSUE THREAD

**Issue by insertish** [revoltchat/delta#128]
Need to store the entire list in-memory so it can be subscribed to.

**Comment by insertish** [comment]
Temporary mitigation would be to just fetch online users which makes the client's job much easier.

**Comment by renhiyama** [comment]
> Need to store the entire list in-memory so it can be subscribed to.

Wouldn't that consume a lot of ram?
Have you considered making a swapfile like method? That is, storing all the users list in an encrypted file and fetching only required ones when needed? Also for a large server, doesn't that mean revolt app will consume a lot of useless space?

**Comment by insertish** [comment]
This issue is superseded by https://github.com/revoltchat/bonfire/issues/2.
