### ISSUE TITLE
"524 A Timeout Occurred" when reply mention field is true

### ISSUE THREAD

**Issue by arslee07** [revoltchat/delta#139]
When sending a message, if in one of the objects of the "answers" array the value of the "mention" field is true, then the server will return status 524 with an empty body, but the message will still be sent.

Curl example:
```bash
$ curl https://api.revolt.chat/channels/<channel_id>/messages \
      -X POST \
      -d '{"content": "curl mention test", "replies": [{"id": "<message_id>", "mention": true}]}' \
      -H 'Content-Type: application/json' \
      -H 'x-session-token: <session token, also reproducible with bot token> '
```

Also, you can see that if all the "mention" fields are false, then the server will successfully return the message object.

**Comment by insertish** [comment]
There was an issue with the Web Push queue, workers did not gracefully restart or handle errors so the queue would get blocked up. Hence requests with mentions never finished.

This was fixed in 119f258b61fdb75be234ecf92124a5a28bc50749.
This also fixed a memory leak.
