### ISSUE TITLE
The edit note is overlapping with the time a message was sent

### ISSUE THREAD

**Issue by sEbi3** [revoltchat/delta#150]
This is how it looks like after a message has been edited. 
![1](https://user-images.githubusercontent.com/44784580/165810882-6ccd219e-7bb0-49cb-a134-a987bc288739.png)

Now, after you're hovering over the edited message it's overlapping with the time the message was sent.
![Screenshot (11)](https://user-images.githubusercontent.com/44784580/165811272-b8ad5536-de04-4592-8a7a-3f6d67f4dafe.png)

A simple soulution would be moving the edit note at the end of a message. Example on Discord:
![Screenshot 2022-04-28 192534](https://user-images.githubusercontent.com/44784580/165811956-e0dabbf6-bbb1-4eb8-90ea-d6ab6c1628ac.png)

**Comment by Rexogamer** [comment]
(Wrong repo - this should moved to [Revite](https://github.com/revoltchat/revite).)

**Comment by sEbi3** [comment]
Alright, I'll move it over to the Revite repo, thanks.
