### ISSUE TITLE
Problem while entering to Revolt Discovery.

### ISSUE THREAD

**Issue by 6vz** [revoltchat/delta#154]
So uhh... I really want to know what went wrong, since i have no f-ing idea...
![Screenshot 2022-04-30 at 19 27 49](https://user-images.githubusercontent.com/92748380/166116027-ec6673d0-29e7-47a5-bd0c-bbbd427f9e8f.png)

**Comment by HigherOrderLogic** [comment]
Iirc just reloading the web page will fix the issue for you.

**Comment by Rexogamer** [comment]
Closing as a non-backend issue - this seems to occur semi-frequently but not consistently enough to diagnose/fix
