### ISSUE TITLE
bug: Deleted messages don't get deleted properly

### ISSUE THREAD

**Issue by janderedev** [revoltchat/delta#165]
### What happened?

Posting in the correct repo this time after github mobile posted my issue to the wrong one.

When deleting a message, the delete event is emitted properly, but the message doesn't seem to be deleted from the database - After reloading the app, the message magically returns.

https://user-images.githubusercontent.com/26145882/168797020-d28037e6-b0bb-4c8e-8b29-92be79e65a23.MOV

**Comment by insertish** [comment]
Fixed in https://github.com/revoltchat/quark/commit/a2d2aa9fc27e55ca5d8603b7ff531449f47a34ac.
