### ISSUE TITLE
Add "nsfw" flags to both channels and servers.

### ISSUE THREAD

**Issue by insertish** [revoltchat/delta#31]
Currently this is handled by the client for channels by checking channel name.

The field should only be serialised if `true`, something like so:

```rust
#[skip_serializing_if = "it is false", default = "false"]
pub nsfw: boolean
```
Note: Prevent Web Push notifications being generated for nsfw channels, or otherwise add a server flag for this.

**Comment by Andre601** [comment]
I would like to add to this, to make the app/server remember what channels you've visited already, because having this 18+ confirmation each time when you switch to the channel is quite frustrating.
