### ISSUE TITLE
Deprecate and remove "Fetch Relationship(s)" routes.

### ISSUE THREAD

**Issue by insertish** [revoltchat/delta#70]
The following two routes should be deprecated:
- [GET /users/relationships](https://developers.revolt.chat/api/#tag/Relationships/paths/~1users~1relationships/get)
- [GET /users/:id/relationship](https://developers.revolt.chat/api/#tag/Relationships/paths/~1users~1:user~1relationship/get)

**Comment by Rexogamer** [comment]
Are there any known uses of these?

**Comment by insertish** [comment]
They're already provided on user objects and elsewhere more readily, so a single request to fetch this information is redundant.
