### ISSUE TITLE
Deleting bot didn't free name 

### ISSUE THREAD

**Issue by Osamu01** [revoltchat/delta#97]
Hello. The bot name in question is 'Fhantom'. This issue has persisted from right after after the deletion of said bot to today (about 40 hrs or so). 

I've since chosen a new name, so I won't be needing this name but I digress this seems like a bug.

**Comment by insertish** [comment]
This name is currently in use by a user. You may have just had terrible timing.

**Comment by Osamu01** [comment]
> This name is currently in use by a user. You may have just had terrible timing.

If it says the user is Fenton, then it's in fact not. I quite literally deleted the bot and then simultaneously tried to re-register the name so I find it hard to believe it was timing. Such an unlikely name to snipe.
